# Generated by Django 3.2.6 on 2021-08-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_homepagepromotional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagepromotional',
            name='image',
            field=models.ImageField(upload_to='promotional_pictures'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
    ]
