# Generated by Django 3.2.6 on 2021-09-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
