# Generated by Django 3.2.6 on 2021-09-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210909_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterUniqueTogether(
            name='sizes',
            unique_together={('size_type', 'product')},
        ),
    ]
