# Generated by Django 3.2.6 on 2021-09-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_quantity'),
        ('cart', '0007_orderedproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
