# Generated by Django 3.2.6 on 2021-09-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20210909_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='user',
        ),
    ]
