# Generated by Django 3.2.6 on 2021-09-22 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210922_1927'),
        ('cart', '0012_auto_20210922_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.IntegerField(default=10)),
                ('paid', models.BooleanField(default=False)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('products', models.ManyToManyField(to='cart.OrderedProduct')),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.shippingaddress')),
            ],
        ),
    ]
