# Generated by Django 3.2.6 on 2021-09-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210922_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='firstname',
            field=models.CharField(default='W', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='street',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='surname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='town',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
