# Generated by Django 3.2.6 on 2021-10-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
